/** Simple Icons CDN slug: https://cdn.simpleicons.org/{slug} */
export const techIconSlug: Record<string, string> = {
  Java: 'java',
  Python: 'python',
  TypeScript: 'typescript',
  JavaScript: 'javascript',
  'C++': 'cplusplus',
  'C#': 'csharp',
  PHP: 'php',
  'HTML/CSS': 'html5',
  React: 'react',
  'React Native': 'react',
  'Vue.js': 'vuedotjs',
  'Next.js': 'nextdotjs',
  Laravel: 'laravel',
  Tailwind: 'tailwindcss',
  'Electron.js': 'electron',
  'Express.js': 'express',
  Django: 'django',
  Bootstrap: 'bootstrap',
  'Node.js': 'nodedotjs',
  Spring: 'spring',
  MySQL: 'mysql',
  PostgreSQL: 'postgresql',
  MongoDB: 'mongodb',
  SQLite: 'sqlite',
  Redis: 'redis',
  Git: 'git',
  Docker: 'docker',
  Azure: 'microsoftazure',
  Firebase: 'firebase',
  'Google Cloud': 'googlecloud',
  'VS Code': 'visualstudiocode',
  PyCharm: 'pycharm',
  Eclipse: 'eclipseide',
  Figma: 'figma',
  Canva: 'canva',
  Unity: 'unity',
  'Unreal Engine': 'unrealengine',
  Godot: 'godotengine',
  'Adobe Premiere Pro': 'adobepremierepro',
  'Adobe Photoshop': 'adobephotoshop',
  'Adobe Illustrator': 'adobeillustrator',
};

export function techIconUrl(name: string): string | null {
  const slug = techIconSlug[name];
  return slug ? `https://cdn.simpleicons.org/${slug}` : null;
}
