'use client'; // This layout uses client-side hooks and event listeners
// Include imports for Lenis
import React, { useEffect, useRef } from 'react';
import Lenis from '@studio-freight/lenis';
import { Poppins } from "next/font/google";
import "./globals.css";
import StaggeredMenu from '@/components/ui/StaggeredMenu';
import '@fortawesome/fontawesome-free/css/all.min.css';

// Define menu items for StaggeredMenu
const menuItems = [
  { label: 'Home', ariaLabel: 'Go to home section', link: 'home' },
  { label: 'About', ariaLabel: 'Learn about Monther', link: 'about' },
  { label: 'Experience', ariaLabel: 'View work experience', link: 'experience' },
  { label: 'Projects', ariaLabel: 'See portfolio projects', link: 'projects' },
  { label: 'Contact', ariaLabel: 'Get in touch', link: 'contact' }
];

// Define social items for StaggeredMenu
const socialItems = [
  { label: 'GitHub', link: 'https://github.com/monthertuwati', icon: 'fab fa-github' },
  { label: 'LinkedIn', link: 'https://www.linkedin.com/in/monthertuwati/', icon: 'fab fa-linkedin' },
  { label: 'Gmail', link: 'mailto:monthertuwati@gmail.com', icon: 'fas fa-envelope' }
];


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// Metadata is for server components, so it stays outside the client component export
// It should ideally be in a separate metadata.ts file in App Router client components
// Keeping it commented out as in your provided code.
/*
  // app/metadata.ts
  import type { Metadata } from 'next';

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
*/


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // --- Lenis Smooth Scrolling Implementation ---
  // Use useRef to hold the Lenis instance
  const lenis = useRef<Lenis | null>(null);

  useEffect(() => {
    // Initialize Lenis only in the browser environment
    if (typeof window !== 'undefined') {
      lenis.current = new Lenis({
        duration: 1.2, // Adjust the duration for scroll speed (seconds)
        easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)), // Easing function (default lenis easing)
        smoothWheel: true, // Enable smooth scrolling for mouse wheel
        // wheelMultiplier: 1, // Adjust scroll speed sensitivity
        // touchMultiplier: 1,
        // infinite: false, // Set to true for infinite looping scrolling
        // autoResize: true, // Automatically handle window resizing
      });

      // This function updates Lenis on each frame using requestAnimationFrame
      function raf(time: number) {
        lenis.current?.raf(time);
        requestAnimationFrame(raf);
      }

      // Start the animation loop
      requestAnimationFrame(raf);

      // Clean up the Lenis instance when the component unmounts
      return () => {
        lenis.current?.destroy();
      };
    }
  }, []); // Empty dependency array ensures this effect runs only once on mount and cleans up on unmount
  // --- End Lenis Implementation ---

  // Smooth scroll to section function
  const scrollToSection = (sectionId: string) => {
    const element = document.getElementById(sectionId);
    if (element && lenis.current) {
      lenis.current.scrollTo(element, {
        offset: -45, // No offset - scroll to exact top of section
        duration: 1.5,
      });
    }
  };

  // Handle menu item clicks
  const handleMenuItemClick = (item: any) => {
    scrollToSection(item.link);
  };

  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased font-poppins bg-[#1A1A1A]`}
      >
         {/* StaggeredMenu Navigation */}
         <StaggeredMenu
           position="right"
           items={menuItems}
           socialItems={socialItems}
           displaySocials={true}
           displayItemNumbering={true}
           menuButtonColor="#fff"
           openMenuButtonColor="#333"
           changeMenuColorOnOpen={true}
           colors={['#1A1A1A', '#2A2A2A']}
           logoUrl="/logo/mt-logo.svg"
           accentColor="#FF6B35"
           isFixed={true}
           onItemClick={handleMenuItemClick}
           onMenuOpen={() => console.log('Menu opened')}
           onMenuClose={() => console.log('Menu closed')}
         />

        {children}

      </body>
    </html>
  );
}
